name: PR Check

on:
  pull_request:
    branches:
    - '*'

jobs:
  branch-naming-rules:
    name: Check Branch Name
    runs-on: ubuntu-latest
    steps:
    - uses: deepakputhraya/action-branch-name@master
      with:
        regex: '([a-z])+\/([a-z])+' # Regex the branch should match. This example enforces grouping
        allowed_prefixes: 'feat,fix,docs,style,refactor,chore' # All branches should start with the given prefix
        ignore: dev,beta,stable # Ignore exactly matching branch names from convention
        min_length: 5 # Min length of the branch name
        max_length: 50 # Max length of the branch name
